CREATE TABLE crypto_transaction (
    "CURRENT_BALANCE_BTC" NUMERIC(38, 2),
    "CURRENT_BALANCE_ETH" NUMERIC(38, 2),
    "CURRENT_BALANCE_USDT" NUMERIC(38, 2),
    "PRICE" NUMERIC(38, 2),
    "QUANTITY" NUMERIC(38, 2),
    "TOTAL" NUMERIC(38, 2),
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "UPDATED_AT" TIMESTAMP(6),
    "USER_ID" BIGINT NOT NULL,
    "SYMBOL" CHARACTER VARYING(255),
    "ORDER_TYPE" ENUM('BUY', 'SELL')
);

CREATE TABLE crypto_price (
  "ASK_PRICE" NUMERIC(18, 8) NOT NULL,
  "BID_PRICE" NUMERIC(18, 8) NOT NULL,
  "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
  "UPDATED_AT" TIMESTAMP(6),
  "SYMBOL" CHARACTER VARYING(50) NOT NULL
);


CREATE TABLE crypto_wallet (
   "BALANCE_BTC" NUMERIC(38, 2),
   "BALANCE_ETH" NUMERIC(38, 2),
   "BALANCE_USDT" NUMERIC(38, 2),
   "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
   "UPDATED_AT" TIMESTAMP(6),
   "USER_ID" BIGINT
);

CREATE TABLE crypto_user (
 "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
 "UPDATED_AT" TIMESTAMP(6)
);
